title: EDM Apple Blog
description: All thing Apple @ RU
theme: just-the-docs

url: https://gmarnin.github.io/apple-blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  EDM Apple Support:
    - https://github.com//apple-blog/docs/support"
  EDM Apple Support 2:
    - https://github.com//apple-blog/docs/support.md"

nav_external_links:
  - title: My Link
    url: https://rutgers.edu
    hide_icon: false
    opens_in_new_tab: true

collections:
  - External Resources
  - Internal Resources
