title: Apple Blog Testing
description: All thing Apple @ RU
theme: just-the-docs

url: https://gmarnin.github.io/apple-blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  "Home":
    - https://github.com/
    - https://apple.com/
