title: Apple Blog Testing
description: All thing Apple @ RU
theme: just-the-docs

url: https://gmarnin.github.io/apple-blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  "Home":
    - https://github.com/
  "Apple":
    - https://apple.com/

nav_external_links:
  - title: My Link
    url: https://rutgers.edu
    hide_icon: false
    opens_in_new_tab: true

---
title: Apple School Manager (ASM) Accounts
nav_order: 1
---
